Remove removed feature
error[E0557]: feature has been removed
 --> src/main.rs:1:44
  |
1 | #![feature(proc_macro_hygiene, decl_macro, const_fn)]
  |                                            ^^^^^^^^ feature has been removed
  |
  = note: split into finer-grained feature gates